import React from 'react';
import { FeaturedSystem, Header, PageGrid, SectionHeading, ThemeProvider } from '../components/SystemUI.jsx';
import useTorontoSignal from '../hooks/useTorontoSignal.js';
import sharinganUrl from '../../assets/mangekyo-threeblade.svg';

function SignalField(){return <div className="signal-field-react" aria-hidden="true"><span className="signal-axis x"/><span className="signal-axis y"/><span className="signal-orbit"/><span className="signal-dot a"/><span className="signal-dot b"/><span className="signal-dot c"/><span className="signal-dot d"/><span className="signal-meta a">FIELD / C3</span><span className="signal-meta c">NODE / ACTIVE</span><span className="signal-meta b">SIGNAL / 2026</span><img className="signal-eye" src={sharinganUrl} alt=""/></div>}

function HomeContent(){
 const weather=useTorontoSignal();
 const nav=[{index:'01',label:'Index',href:'#index'},{index:'02',label:'Work',href:'#work'},{index:'03',label:'Archive',href:'#archive'},{index:'04',label:'Notes',href:'#notes'},{index:'05',label:'About',href:'#about'}];
 return <div className="c3-app"><PageGrid/><Header nav={nav} status="CLYD3 SYSTEM / ONLINE" weather={weather}/><main id="top">
 <section className="home-hero c3-shell"><div className="home-hero-copy"><p className="c3-eyebrow"><span>001</span>CLYD3 / DIGITAL HOME</p><h1>Building at the intersection of <em>ideas</em>, systems <span className="serif">&amp; culture.</span></h1><p className="home-hero-intro">An evolving archive of work, experiments, photographs and things worth remembering.</p><div className="home-hero-actions"><a className="home-text-link" href="#index">Explore the index <span>↘</span></a><a className="home-text-link muted" href="#about">About this space <span>→</span></a></div></div><div className="home-hero-visual"><SignalField/></div><div className="home-hero-meta"><span>Independent digital archive</span><span>Signal / work / memory</span><span>2026</span></div></section>
 <section className="c3-section c3-shell" aria-labelledby="featured-title"><div className="featured-intro"><div><p className="c3-eyebrow"><span>008–009</span>FEATURED SYSTEMS</p><h2 id="featured-title" style={{margin:0,fontSize:'clamp(34px,4vw,58px)',letterSpacing:'-.055em',fontWeight:500}}>Interactive records,<br/>built from lived data.</h2></div><p>Two standalone CLYD3 systems turn personal archives into explorable interfaces. Each opens separately so the main site stays in place while you move deeper into the data.</p></div><div className="featured-grid"><FeaturedSystem index="08" title="FUT Club Intelligence" description="Explore 489 FUT players through usage, performance, evolution paths, squad depth and club-wide patterns." href="/fut/" meta="FOOTBALL / CLUB DATA / INTERACTIVE"/><FeaturedSystem index="09" title="Listening Atlas" description="Explore a decade of listening through artists, sonic trends, platform overlap and the weighted all-time Love Index." href="/music/" meta="MUSIC / 2016–2025 / INTERACTIVE" accent="crimson"/></div></section>
 <section className="c3-section c3-shell" id="index"><SectionHeading index="002" eyebrow="INDEX" title="Four ways into the system."/><div className="system-index-grid">{[['01','Work','Projects, systems, analysis and things made to solve real problems.','#work'],['02','Lab','Small builds, prototypes, code studies and ideas still becoming.','#lab'],['03','Archive','Photography, visual observations and fragments collected over time.','#archive'],['04','Notes','Short essays, questions, frameworks and things worth remembering.','#notes']].map(([n,t,p,h])=><a className="system-index-card" href={h} key={t}><small>{n} / NAVIGATION</small><h3>{t}</h3><p>{p}</p></a>)}</div></section>
 <section className="c3-section c3-shell" id="work"><SectionHeading index="003" eyebrow="SELECTED WORK" title={<>Systems, stories<br/>and useful things.</>} note="A working index. Detailed case studies will live here as the site grows."/><div className="practice-field">{[['01','Field / Evidence','Data & Impact','Analysis / evidence / decision support'],['02','Field / Infrastructure','Digital Systems','Tools / workflows / infrastructure'],['03','Field / Interaction','Creative Experiments','Web / visual systems / interaction']].map(([n,m,t,p])=><article className="practice-card" key={t}><div className="top"><span>{n}</span><span>{m}</span></div><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="home-about c3-shell" id="about"><div className="home-about-index">004 / ABOUT</div><div className="home-about-copy"><strong>Not a résumé on a webpage.</strong><p>CLYD3 is intended to become a living record of work, curiosity and creative practice: a place where finished projects can sit beside unfinished questions.</p></div><div className="home-about-mark">↘</div></section>
 <section className="c3-section c3-shell" id="lab"><div className="coming-grid"><article className="coming-card" id="archive"><p className="c3-eyebrow"><span>005</span>ARCHIVE</p><h3>Images as memory.</h3><p>A visual archive will live here — quiet, chronological and deliberately separate from project work.</p><small>In development</small></article><article className="coming-card" id="notes"><p className="c3-eyebrow"><span>006</span>NOTES</p><h3>Thinking in public.</h3><p>Short-form observations, longer essays and useful frameworks without the machinery of a traditional blog.</p><small>In development</small></article></div></section>
 <section className="c3-section c3-shell" id="contact"><p className="c3-eyebrow"><span>007</span>CONTACT</p><div className="contact-block"><h2>Have something<br/>worth building?</h2><div className="contact-links"><a href="https://github.com/mukanzi" target="_blank" rel="noopener noreferrer"><span>GitHub / mukanzi</span><span>↗</span></a><a href="#top"><span>Back to top</span><span>↑</span></a></div></div></section>
 </main><footer className="c3-footer"><span>CLYD3</span><span>Designed &amp; built as an evolving system.</span><span>© {new Date().getFullYear()}</span></footer></div>;
}
export default function HomeApp(){return <ThemeProvider><HomeContent/></ThemeProvider>}
